### ISSUE TITLE
Sıkça Sorulan Sorular

### ISSUE THREAD

**Issue by hkulekci** [eryader/dokunduyogren.com#3]
**Eryader Nedir?** 
Kapsayıcı ve Erişilebilir Yaşam Derneği 2021 Yılında kurulmuş ancak 2019 yılından beri projeler geliştiren bir STK dır.  Dernek, görme engelli bireyler için kapsayıcılık, eşitlik, hak temelli yaklaşım ve adalete dayalı politikalar geliştirmek ve engelli bireylerin eğitim ortamlarına tam katılımını desteklemek amacıyla kurulmuştur.

**Dokunsal Resim/Kitap nedir?** 
Dokunsal resimler yükseltilmiş/kabartılmış çizgiler, alanlar, dokular, etiketler ve
sembollerden oluşan ve görünmekten çok hissedilmesi amaçlanan  dokunsal görselleştirmedir. 
Ya da bakılmak yerine dokunulmak üzere tasarlanmış resimlerdir /görüntülerdir.
Görme engelliler tarafından algılanabilen gerçekliğin temsilleridir..

**Ne değildir?**
Baskı resmin düz bir kopyası değildir. Renk,süsleme, sanatsal eklemeler gibi görsel okuycuların beklediği sembolleri içermez.

**Dokunsal kitabı indirmek ücretsiz mi?**
Görme yetersizliği olan bireylerin bilgiye erişimini sağlamak için oluşturulduğu için istediğimiz kadar dokunsal kitaptan resimler indirebilirsiniz. Ancak bunları satmak istiyorsanız, onayımız olmadan yapamazsınız. Lütfen bizimle iletişime geçiniz (Adres).
Kütüphanemizde dokunsal kitap katalogları  nelerden oluşabilir?
Kütüphanemizdeki dokunsal kitaplar nesneler, farklı bilim alanları veya haritalar gibi çok çeşitli konuları kapsayabilir.

**Kütüphane de yeni dokunsal kitapların üretilmesine nasıl destek olabilirim?**
Gönüllü olarak kütüphanenin zenginleştirmeye yönelik bölümler oluşturabilir, çizebilir veya betimlemeler ile yardımcı olabilirsiniz.

**Mobil uygulama ücretsiz olarak indirilebilir mi?**
Evet, Apple mobil araçlarından “Tactile İmage Reader” uygulamasını indirerek rahatlıkla dokunsal resim ile etkileşime girebilirsiniz ve bireysel öğrenmenizi kendi hızınızda bağımsız olarak gerçekleştirebilirsiniz.

**Comment by muzaffercankaplan** [comment]
bu kısım tamamdır abi.

**Comment by hkulekci** [comment]
👏
